# Generated by Django 4.1.7 on 2023-04-15 10:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_used_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
