# Generated by Django 4.1.7 on 2023-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_alter_used_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used',
            name='image',
            field=models.ImageField(upload_to='used/'),
        ),
    ]
