# Generated by Django 4.1.7 on 2023-04-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_used_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/used/'),
        ),
    ]
