# Generated by Django 4.1.7 on 2023-04-21 05:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('disc_price', models.FloatField(blank=True, null=True)),
                ('lot_size', models.IntegerField()),
                ('min_lot', models.IntegerField()),
                ('gst_req', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('contact', phone_field.models.PhoneField(max_length=31)),
                ('description_short', models.CharField(max_length=50)),
                ('description_long', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/business/')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gst_req',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_lot',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Items/'),
        ),
    ]
