# Generated by Django 4.1.7 on 2023-05-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
    ]
