# Generated by Django 4.1.7 on 2023-05-11 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0014_rename_category_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description_short', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Orders/')),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('pincode', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description_short', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Cart/')),
                ('state', models.CharField(default='', max_length=20)),
                ('district', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
