# Generated by Django 4.1.7 on 2023-05-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_orders_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='dprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='dprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
