# Generated by Django 4.1.7 on 2023-05-14 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_remove_orders_qty_orders_name_orders_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timeplaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 16, 20, 56, 485528, tzinfo=datetime.timezone.utc)),
        ),
    ]
