# Generated by Django 4.1.7 on 2023-05-14 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_orders_status_alter_orders_timeplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timeplaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 17, 3, 37, 439079, tzinfo=datetime.timezone.utc)),
        ),
    ]
