# Generated by Django 4.1.7 on 2023-05-19 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_alter_business_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description_short',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='description_short',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timeplaced',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 14, 23, 1, 603019, tzinfo=datetime.timezone.utc)),
        ),
    ]
